BetterEnderChest:
  lastModifiedByVersion: 2.4.8
  language: en
  useUUIDs: true
  drop: OBSIDIAN
  dropSilkTouch: ITSELF
  dropCreative: NOTHING
  enderChestCompatibilityMode: true
  showDebugMessages: false
  lockChestsOnError: true
  manualWorldgroupManagement: false
AutoSave:
  autoSaveIntervalSeconds: 5
IllegalItems:
- check: itemType
  for: COAL
- check: itemType
  for: GOLD_ORE
- check: itemType
  for: GOLD_INGOT
- check: itemType
  for: GOLD_NUGGET
- check: itemType
  for: COBBLESTONE
- check: itemType
  for: STONE
- check: itemType
  for: LAPIS_ORE
- check: itemType
  for: INK_SACK
- check: itemType
  for: IRON_ORE
- check: itemType
  for: IRON_INGOT
- check: itemType
  for: IRON_NUGGET
- check: itemType
  for: REDSTONE_ORE
- check: itemType
  for: REDSTONE
- check: itemType
  for: DIAMOND_ORE
- check: itemType
  for: DIAMOND
- check: itemType
  for: EMERALD_ORE
- check: itemType
  for: EMERALD
- check: itemType
  for: QUARTZ_ORE
- check: itemType
  for: QUARTZ
- check: itemType
  for: LOG
- check: itemType
  for: LOG:1
- check: itemType
  for: LOG:2
- check: itemType
  for: LOG:3
- check: itemType
  for: LOG_2:1
- check: itemType
  for: LOG_2
- check: itemType
  for: RED_MUSHROOM
- check: itemType
  for: BROWN_MUSHROOM
- check: itemType
  for: HUGE_MUSHROOM_1
- check: itemType
  for: HUGE_MUSHROOM_2
- check: itemType
  for: PUMPKIN
- check: itemType
  for: PORK
- check: itemType
  for: RAW_CHICKEN
- check: itemType
  for: FEATHER
- check: itemType
  for: EGG
- check: itemType
  for: MUTTON
- check: itemType
  for: WOOL
- check: itemType
  for: RABBIT
- check: itemType
  for: RABBIT_HIDE
- check: itemType
  for: RABBIT_FOOT
- check: itemType
  for: RAW_BEEF
- check: itemType
  for: LEATHER
- check: itemType
  for: RAW_FISH
- check: itemType
  for: PRISMARINE_SHARD
- check: itemType
  for: DIAMOND_PICKAXE
- check: itemType
  for: DIAMOND_AXE
- check: itemType
  for: DIAMOND_SWORD
- check: itemType
  for: IRON_PICKAXE
- check: itemType
  for: IRON_AXE
- check: itemType
  for: IRON_SWORD
- check: itemType
  for: GOLD_PICKAXE
- check: itemType
  for: GOLD_SWORD
- check: itemType
  for: GOLD_AXE
- check: itemType
  for: STONE_PICKAXE
- check: itemType
  for: STONE_AXE
- check: itemType
  for: STONE_SWORD
- check: itemType
  for: WOOD_PICKAXE
- check: itemType
  for: WOOD_SWORD
- check: itemType
  for: WOOD_AXE
- check: itemType
  for: CHEST
- check: itemType
  for: GOLD_BLOCK
- check: itemType
  for: IRON_BLOCK
- check: itemType
  for: DIAMOND_BLOCK
- check: itemType
  for: REDSTONE_BLOCK
- check: itemType
  for: EMERALD_BLOCK
- check: itemType
  for: LAPIS_BLOCK
- check: itemType
  for: COAL_BLOCK
PrivateEnderChest:
  rankUpgrades: 3
  defaultSlots: 27
  slotsUpgrade1: 36
  slotsUpgrade2: 45
  slotsUpgrade3: 54
PublicEnderChest:
  showOnOpeningUnprotectedChest: false
  showOnUsingCommand: false
  defaultSlots: 27
Database:
  enabled: false
  host: localhost
  port: 3306
  databaseName: minecraft
  username: root
  password: ''
  useUtf8: true
